/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookmyticket;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Base64;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author HP
 */
public class AddMovies extends javax.swing.JFrame {

    String path,fn;

    public AddMovies() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mvn = new javax.swing.JTextField();
        prc = new javax.swing.JTextField();
        loc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        de = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        lblpicture = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        th = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Movie details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 240, 40));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Movie Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Price:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 130, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Location:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 130, 50));

        mvn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mvnActionPerformed(evt);
            }
        });
        getContentPane().add(mvn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 220, 30));

        prc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prcActionPerformed(evt);
            }
        });
        getContentPane().add(prc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 220, 30));
        getContentPane().add(loc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 220, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Description:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 90, 30));

        de.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deActionPerformed(evt);
            }
        });
        getContentPane().add(de, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 220, 30));

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 700, 110, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Photo:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 80, 20));

        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 220, 170));

        lblpicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblpicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 190, 170));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Theater:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        getContentPane().add(th, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 220, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 710, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new Admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mvnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mvnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mvnActionPerformed

    private void prcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prcActionPerformed

    private void deActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deActionPerformed

    public boolean is_registered(Connection con, String mn) {
        try {
            String s = "select * From movies Where location='" + mn + "'";
            PreparedStatement ps = con.prepareStatement(s);
            ResultSet r = ps.executeQuery();
            int cnt = 0;
            if (r.next()) {
                cnt++;
            }
            if (cnt == 0) {
                return false;
            }

        } catch (SQLException ex) {
            Logger.getLogger(AddMovies.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String mn = mvn.getText();
        String the = th.getText();
        String p = prc.getText();
        String lc = loc.getText();
        String des = de.getText();
         
        try {
            //InputStream is = new FileInputStream(new File(path));
 
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/bookmyshow";
            String name = "root";
            String pass = "";
            Connection con = DriverManager.getConnection(url, name, pass);
            if (is_registered(con, lc)) {
                JOptionPane.showMessageDialog(this, "Already Added!");
                return;
            }
            
            
            
            try {
                String dest = "D:\\BookMyTicket\\src\\dbasset\\"+mn+".jpeg";
                
                try {
                     File destinationFile = new File(dest);
            if (!destinationFile.exists()) {
                // Create the destination file if it doesn't exist
                destinationFile.createNewFile();
            }
                    // Create input stream from source file
                    FileInputStream fis = new FileInputStream(path);
                    
                    // Create output stream to destination file
                    FileOutputStream fos = new FileOutputStream(dest);
                    
                    // Create byte array to hold data temporarily
                    byte[] buffer = new byte[1024];
                    int length;
                    
                    // Read from input stream and write to output stream
                    while ((length = fis.read(buffer)) > 0) {
                        fos.write(buffer, 0, length);
                    }
                    
                    // Close streams
                    fis.close();
                    fos.close();
                    
                    System.out.println("Image file copied successfully");
                } catch (IOException e) {
                    System.err.println("Error copying image file: " + e.getMessage());
                }
                
                String s = "insert into movies(mName,TheaterName,price,location,Description,Photos) values('" + mn + "','" +the+ "','" + p + "','" + lc + "','" + des + "','" +mn+ ".jpeg')";
                PreparedStatement pstmt = con.prepareStatement(s);

                if ("".equals(loc.getText())) {
                    JOptionPane.showMessageDialog(this, "Fill al blanks correctly!\nPlease try again!\n");
                } else {
                     pstmt.execute();
                    JOptionPane.showMessageDialog(this, "Added movie SUCCESSFUL\n");
                    mvn.setText("");
                    th.setText("");
                    prc.setText("");
                    loc.setText("");
                    de.setText("");
                    lblpicture.setText("");

                }
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
                Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMovies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.showOpenDialog(null);
        File f = jf.getSelectedFile();
        path = f.getAbsolutePath();
        fn=f.getName();
        path=path.replace("\\","\\\\");
        System.out.print(path);
       
        try {

            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(190, 170, Image.SCALE_SMOOTH);
            ImageIcon ii = new ImageIcon(img);
            lblpicture.setIcon(ii);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMovies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMovies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField de;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpicture;
    private javax.swing.JTextField loc;
    private javax.swing.JTextField mvn;
    private javax.swing.JTextField prc;
    private javax.swing.JTextField th;
    // End of variables declaration//GEN-END:variables
}
